# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a3_option_pricer.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OptionPricer(object):
    def setupUi(self, OptionPricer):
        OptionPricer.setObjectName("OptionPricer")
        OptionPricer.resize(784, 625)
        OptionPricer.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.HongKong))
        self.centralwidget = QtWidgets.QWidget(OptionPricer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 110, 160, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox_kindof_option = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_kindof_option.setIconSize(QtCore.QSize(16, 30))
        self.comboBox_kindof_option.setObjectName("comboBox_kindof_option")
        self.comboBox_kindof_option.addItem("")
        self.comboBox_kindof_option.addItem("")
        self.comboBox_kindof_option.addItem("")
        self.comboBox_kindof_option.addItem("")
        self.verticalLayout.addWidget(self.comboBox_kindof_option)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(230, 100, 161, 61))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_call = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_call.setGeometry(QtCore.QRect(20, 20, 89, 16))
        self.radioButton_call.setChecked(True)
        self.radioButton_call.setObjectName("radioButton_call")
        self.radioButton_put = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_put.setGeometry(QtCore.QRect(20, 40, 89, 16))
        self.radioButton_put.setObjectName("radioButton_put")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(560, 110, 101, 16))
        self.label_result.setObjectName("label_result")
        self.pushButton_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calculate.setGeometry(QtCore.QRect(560, 80, 91, 31))
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.label_result_value = QtWidgets.QLabel(self.centralwidget)
        self.label_result_value.setGeometry(QtCore.QRect(560, 130, 131, 31))
        self.label_result_value.setFrameShape(QtWidgets.QFrame.Box)
        self.label_result_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_result_value.setText("")
        self.label_result_value.setObjectName("label_result_value")
        self.groupBox_asset1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_asset1.setGeometry(QtCore.QRect(230, 180, 161, 371))
        self.groupBox_asset1.setObjectName("groupBox_asset1")
        self.splitter = QtWidgets.QSplitter(self.groupBox_asset1)
        self.splitter.setGeometry(QtCore.QRect(20, 11, 121, 351))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_stock_price = QtWidgets.QLabel(self.splitter)
        self.label_stock_price.setObjectName("label_stock_price")
        self.lineEdit_stock_price = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_stock_price.setObjectName("lineEdit_stock_price")
        self.label_strike_price = QtWidgets.QLabel(self.splitter)
        self.label_strike_price.setObjectName("label_strike_price")
        self.lineEdit_strike_price = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_strike_price.setObjectName("lineEdit_strike_price")
        self.label_strike_price_2 = QtWidgets.QLabel(self.splitter)
        self.label_strike_price_2.setObjectName("label_strike_price_2")
        self.lineEdit_rate = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_rate.setObjectName("lineEdit_rate")
        self.label_vol1 = QtWidgets.QLabel(self.splitter)
        self.label_vol1.setObjectName("label_vol1")
        self.lineEdit_vol1 = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_vol1.setObjectName("lineEdit_vol1")
        self.label_maturity = QtWidgets.QLabel(self.splitter)
        self.label_maturity.setObjectName("label_maturity")
        self.lineEdit_maturity = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_maturity.setObjectName("lineEdit_maturity")
        self.label_step = QtWidgets.QLabel(self.splitter)
        self.label_step.setObjectName("label_step")
        self.lineEdit_step = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_step.setText("")
        self.lineEdit_step.setObjectName("lineEdit_step")
        self.label_paths = QtWidgets.QLabel(self.splitter)
        self.label_paths.setObjectName("label_paths")
        self.lineEdit_path = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_path.setText("")
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.widget_asian_pars = QtWidgets.QWidget(self.centralwidget)
        self.widget_asian_pars.setGeometry(QtCore.QRect(50, 190, 161, 261))
        self.widget_asian_pars.setObjectName("widget_asian_pars")
        self.verticalLayout_asian_pars = QtWidgets.QVBoxLayout(self.widget_asian_pars)
        self.verticalLayout_asian_pars.setObjectName("verticalLayout_asian_pars")
        self.groupBox_numof_assets = QtWidgets.QGroupBox(self.widget_asian_pars)
        self.groupBox_numof_assets.setAutoFillBackground(False)
        self.groupBox_numof_assets.setFlat(False)
        self.groupBox_numof_assets.setCheckable(False)
        self.groupBox_numof_assets.setObjectName("groupBox_numof_assets")
        self.radioButton_asset_single = QtWidgets.QRadioButton(self.groupBox_numof_assets)
        self.radioButton_asset_single.setGeometry(QtCore.QRect(20, 20, 89, 16))
        self.radioButton_asset_single.setChecked(True)
        self.radioButton_asset_single.setObjectName("radioButton_asset_single")
        self.radioButton_asset_basket = QtWidgets.QRadioButton(self.groupBox_numof_assets)
        self.radioButton_asset_basket.setGeometry(QtCore.QRect(20, 50, 89, 16))
        self.radioButton_asset_basket.setObjectName("radioButton_asset_basket")
        self.verticalLayout_asian_pars.addWidget(self.groupBox_numof_assets)
        self.groupBox_pricing_type = QtWidgets.QGroupBox(self.widget_asian_pars)
        self.groupBox_pricing_type.setObjectName("groupBox_pricing_type")
        self.radioButton_type_geo = QtWidgets.QRadioButton(self.groupBox_pricing_type)
        self.radioButton_type_geo.setGeometry(QtCore.QRect(20, 20, 89, 16))
        self.radioButton_type_geo.setChecked(True)
        self.radioButton_type_geo.setObjectName("radioButton_type_geo")
        self.radioButton_type_arith = QtWidgets.QRadioButton(self.groupBox_pricing_type)
        self.radioButton_type_arith.setGeometry(QtCore.QRect(20, 50, 89, 16))
        self.radioButton_type_arith.setObjectName("radioButton_type_arith")
        self.verticalLayout_asian_pars.addWidget(self.groupBox_pricing_type)
        self.groupBox_control_variate = QtWidgets.QGroupBox(self.widget_asian_pars)
        self.groupBox_control_variate.setObjectName("groupBox_control_variate")
        self.radioButton_cv_standard = QtWidgets.QRadioButton(self.groupBox_control_variate)
        self.radioButton_cv_standard.setGeometry(QtCore.QRect(20, 20, 89, 16))
        self.radioButton_cv_standard.setChecked(True)
        self.radioButton_cv_standard.setObjectName("radioButton_cv_standard")
        self.radioButton_cv_geo = QtWidgets.QRadioButton(self.groupBox_control_variate)
        self.radioButton_cv_geo.setGeometry(QtCore.QRect(20, 50, 89, 16))
        self.radioButton_cv_geo.setObjectName("radioButton_cv_geo")
        self.verticalLayout_asian_pars.addWidget(self.groupBox_control_variate)
        self.widget_asset2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_asset2.setGeometry(QtCore.QRect(410, 180, 161, 331))
        self.widget_asset2.setObjectName("widget_asset2")
        self.lineEdit_corr = QtWidgets.QLineEdit(self.widget_asset2)
        self.lineEdit_corr.setGeometry(QtCore.QRect(20, 300, 121, 24))
        self.lineEdit_corr.setText("")
        self.lineEdit_corr.setObjectName("lineEdit_corr")
        self.label_corr = QtWidgets.QLabel(self.widget_asset2)
        self.label_corr.setGeometry(QtCore.QRect(20, 280, 121, 15))
        self.label_corr.setObjectName("label_corr")
        self.groupBox_asset2 = QtWidgets.QGroupBox(self.widget_asset2)
        self.groupBox_asset2.setGeometry(QtCore.QRect(0, 0, 161, 261))
        self.groupBox_asset2.setObjectName("groupBox_asset2")
        self.label_stock_price_2 = QtWidgets.QLabel(self.groupBox_asset2)
        self.label_stock_price_2.setGeometry(QtCore.QRect(20, 30, 121, 15))
        self.label_stock_price_2.setObjectName("label_stock_price_2")
        self.label_vol2 = QtWidgets.QLabel(self.groupBox_asset2)
        self.label_vol2.setGeometry(QtCore.QRect(20, 180, 121, 15))
        self.label_vol2.setObjectName("label_vol2")
        self.lineEdit_vol2 = QtWidgets.QLineEdit(self.groupBox_asset2)
        self.lineEdit_vol2.setGeometry(QtCore.QRect(20, 200, 121, 24))
        self.lineEdit_vol2.setObjectName("lineEdit_vol2")
        self.lineEdit_stock_price_2 = QtWidgets.QLineEdit(self.groupBox_asset2)
        self.lineEdit_stock_price_2.setGeometry(QtCore.QRect(20, 50, 121, 24))
        self.lineEdit_stock_price_2.setObjectName("lineEdit_stock_price_2")
        OptionPricer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OptionPricer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 784, 23))
        self.menubar.setObjectName("menubar")
        self.menuAa = QtWidgets.QMenu(self.menubar)
        self.menuAa.setObjectName("menuAa")
        OptionPricer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OptionPricer)
        self.statusbar.setObjectName("statusbar")
        OptionPricer.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(OptionPricer)
        self.toolBar.setObjectName("toolBar")
        OptionPricer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAbout = QtWidgets.QAction(OptionPricer)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(OptionPricer)
        self.actionExit.setObjectName("actionExit")
        self.actionReadme = QtWidgets.QAction(OptionPricer)
        self.actionReadme.setObjectName("actionReadme")
        self.actionReset = QtWidgets.QAction(OptionPricer)
        self.actionReset.setObjectName("actionReset")
        self.menuAa.addAction(self.actionAbout)
        self.menuAa.addAction(self.actionExit)
        self.menubar.addAction(self.menuAa.menuAction())
        self.toolBar.addAction(self.actionReset)

        self.retranslateUi(OptionPricer)
        QtCore.QMetaObject.connectSlotsByName(OptionPricer)

    def retranslateUi(self, OptionPricer):
        _translate = QtCore.QCoreApplication.translate
        OptionPricer.setWindowTitle(_translate("OptionPricer", "Option Pricer by Group 19"))
        self.label.setText(_translate("OptionPricer", "Exercise Style:"))
        self.comboBox_kindof_option.setItemText(0, _translate("OptionPricer", "European"))
        self.comboBox_kindof_option.setItemText(1, _translate("OptionPricer", "American"))
        self.comboBox_kindof_option.setItemText(2, _translate("OptionPricer", "Asian"))
        self.comboBox_kindof_option.setItemText(3, _translate("OptionPricer", "Implied Volatility"))
        self.groupBox.setTitle(_translate("OptionPricer", "Option Type:"))
        self.radioButton_call.setText(_translate("OptionPricer", "Call"))
        self.radioButton_put.setText(_translate("OptionPricer", "Put"))
        self.label_result.setText(_translate("OptionPricer", "Result:"))
        self.pushButton_calculate.setText(_translate("OptionPricer", "Calculate"))
        self.groupBox_asset1.setTitle(_translate("OptionPricer", "Asset1"))
        self.label_stock_price.setText(_translate("OptionPricer", "Stock Price: ($)"))
        self.label_strike_price.setText(_translate("OptionPricer", "Strike Price: ($)"))
        self.label_strike_price_2.setText(_translate("OptionPricer", "Interest Rate: (%)"))
        self.label_vol1.setText(_translate("OptionPricer", "Volatility: (%)"))
        self.label_maturity.setText(_translate("OptionPricer", "Maturity: (years)"))
        self.label_step.setText(_translate("OptionPricer", "Step:"))
        self.label_paths.setText(_translate("OptionPricer", "Path:"))
        self.groupBox_numof_assets.setTitle(_translate("OptionPricer", "Number of assets:"))
        self.radioButton_asset_single.setText(_translate("OptionPricer", "Single"))
        self.radioButton_asset_basket.setText(_translate("OptionPricer", "Basket"))
        self.groupBox_pricing_type.setTitle(_translate("OptionPricer", "Type of pricer:"))
        self.radioButton_type_geo.setText(_translate("OptionPricer", "Geometric"))
        self.radioButton_type_arith.setText(_translate("OptionPricer", "Arithmetic"))
        self.groupBox_control_variate.setTitle(_translate("OptionPricer", "Control Variate:"))
        self.radioButton_cv_standard.setText(_translate("OptionPricer", "None"))
        self.radioButton_cv_geo.setText(_translate("OptionPricer", "Geometric"))
        self.label_corr.setText(_translate("OptionPricer", "Correlation: (%)"))
        self.groupBox_asset2.setTitle(_translate("OptionPricer", "Asset 2"))
        self.label_stock_price_2.setText(_translate("OptionPricer", "Stock Price: ($)"))
        self.label_vol2.setText(_translate("OptionPricer", "Volatility: (%)"))
        self.menuAa.setTitle(_translate("OptionPricer", "Program"))
        self.toolBar.setWindowTitle(_translate("OptionPricer", "toolBar"))
        self.actionAbout.setText(_translate("OptionPricer", "About"))
        self.actionAbout.setShortcut(_translate("OptionPricer", "F12"))
        self.actionExit.setText(_translate("OptionPricer", "Exit"))
        self.actionExit.setShortcut(_translate("OptionPricer", "Esc"))
        self.actionReadme.setText(_translate("OptionPricer", "readme"))
        self.actionReset.setText(_translate("OptionPricer", "Reset"))
        self.actionReset.setToolTip(_translate("OptionPricer", "Reset"))

