# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a3_option_pricer.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OptionPricer(object):
    def setupUi(self, OptionPricer):
        OptionPricer.setObjectName("OptionPricer")
        OptionPricer.resize(784, 625)
        OptionPricer.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.HongKong))
        self.centralwidget = QtWidgets.QWidget(OptionPricer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 80, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox_kindof_option = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.comboBox_kindof_option.setFont(font)
        self.comboBox_kindof_option.setIconSize(QtCore.QSize(16, 30))
        self.comboBox_kindof_option.setObjectName("comboBox_kindof_option")
        self.comboBox_kindof_option.addItem("")
        self.comboBox_kindof_option.addItem("")
        self.comboBox_kindof_option.addItem("")
        self.comboBox_kindof_option.addItem("")
        self.verticalLayout.addWidget(self.comboBox_kindof_option)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(210, 80, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.radioButton_call = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_call.setGeometry(QtCore.QRect(20, 20, 89, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.radioButton_call.setFont(font)
        self.radioButton_call.setChecked(True)
        self.radioButton_call.setObjectName("radioButton_call")
        self.radioButton_put = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_put.setGeometry(QtCore.QRect(20, 40, 89, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.radioButton_put.setFont(font)
        self.radioButton_put.setObjectName("radioButton_put")
        self.pushButton_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calculate.setGeometry(QtCore.QRect(590, 230, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_calculate.setFont(font)
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.groupBox_asset1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_asset1.setGeometry(QtCore.QRect(210, 160, 161, 371))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.groupBox_asset1.setFont(font)
        self.groupBox_asset1.setObjectName("groupBox_asset1")
        self.splitter = QtWidgets.QSplitter(self.groupBox_asset1)
        self.splitter.setGeometry(QtCore.QRect(20, 11, 121, 351))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.splitter.setFont(font)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_stock_price = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_stock_price.setFont(font)
        self.label_stock_price.setObjectName("label_stock_price")
        self.lineEdit_stock_price = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit_stock_price.setFont(font)
        self.lineEdit_stock_price.setObjectName("lineEdit_stock_price")
        self.label_strike_price = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_strike_price.setFont(font)
        self.label_strike_price.setObjectName("label_strike_price")
        self.lineEdit_strike_price = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit_strike_price.setFont(font)
        self.lineEdit_strike_price.setObjectName("lineEdit_strike_price")
        self.label_strike_price_2 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_strike_price_2.setFont(font)
        self.label_strike_price_2.setObjectName("label_strike_price_2")
        self.lineEdit_rate = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit_rate.setFont(font)
        self.lineEdit_rate.setObjectName("lineEdit_rate")
        self.label_vol1 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_vol1.setFont(font)
        self.label_vol1.setObjectName("label_vol1")
        self.lineEdit_vol1 = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit_vol1.setFont(font)
        self.lineEdit_vol1.setObjectName("lineEdit_vol1")
        self.label_maturity = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_maturity.setFont(font)
        self.label_maturity.setObjectName("label_maturity")
        self.lineEdit_maturity = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit_maturity.setFont(font)
        self.lineEdit_maturity.setObjectName("lineEdit_maturity")
        self.label_step = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_step.setFont(font)
        self.label_step.setObjectName("label_step")
        self.lineEdit_step = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit_step.setFont(font)
        self.lineEdit_step.setText("")
        self.lineEdit_step.setObjectName("lineEdit_step")
        self.label_paths = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_paths.setFont(font)
        self.label_paths.setObjectName("label_paths")
        self.lineEdit_path = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit_path.setFont(font)
        self.lineEdit_path.setText("")
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.widget_asian_pars = QtWidgets.QWidget(self.centralwidget)
        self.widget_asian_pars.setGeometry(QtCore.QRect(40, 160, 161, 311))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.widget_asian_pars.setFont(font)
        self.widget_asian_pars.setObjectName("widget_asian_pars")
        self.verticalLayout_asian_pars = QtWidgets.QVBoxLayout(self.widget_asian_pars)
        self.verticalLayout_asian_pars.setObjectName("verticalLayout_asian_pars")
        self.groupBox_numof_assets = QtWidgets.QGroupBox(self.widget_asian_pars)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.groupBox_numof_assets.setFont(font)
        self.groupBox_numof_assets.setAutoFillBackground(False)
        self.groupBox_numof_assets.setFlat(False)
        self.groupBox_numof_assets.setCheckable(False)
        self.groupBox_numof_assets.setObjectName("groupBox_numof_assets")
        self.radioButton_asset_single = QtWidgets.QRadioButton(self.groupBox_numof_assets)
        self.radioButton_asset_single.setGeometry(QtCore.QRect(20, 20, 89, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.radioButton_asset_single.setFont(font)
        self.radioButton_asset_single.setChecked(True)
        self.radioButton_asset_single.setObjectName("radioButton_asset_single")
        self.radioButton_asset_basket = QtWidgets.QRadioButton(self.groupBox_numof_assets)
        self.radioButton_asset_basket.setGeometry(QtCore.QRect(20, 50, 89, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.radioButton_asset_basket.setFont(font)
        self.radioButton_asset_basket.setObjectName("radioButton_asset_basket")
        self.verticalLayout_asian_pars.addWidget(self.groupBox_numof_assets)
        self.groupBox_pricing_type = QtWidgets.QGroupBox(self.widget_asian_pars)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.groupBox_pricing_type.setFont(font)
        self.groupBox_pricing_type.setObjectName("groupBox_pricing_type")
        self.radioButton_type_geo = QtWidgets.QRadioButton(self.groupBox_pricing_type)
        self.radioButton_type_geo.setGeometry(QtCore.QRect(20, 20, 89, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.radioButton_type_geo.setFont(font)
        self.radioButton_type_geo.setChecked(True)
        self.radioButton_type_geo.setObjectName("radioButton_type_geo")
        self.radioButton_type_arith = QtWidgets.QRadioButton(self.groupBox_pricing_type)
        self.radioButton_type_arith.setGeometry(QtCore.QRect(20, 50, 89, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.radioButton_type_arith.setFont(font)
        self.radioButton_type_arith.setObjectName("radioButton_type_arith")
        self.verticalLayout_asian_pars.addWidget(self.groupBox_pricing_type)
        self.groupBox_control_variate = QtWidgets.QGroupBox(self.widget_asian_pars)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.groupBox_control_variate.setFont(font)
        self.groupBox_control_variate.setObjectName("groupBox_control_variate")
        self.radioButton_cv_standard = QtWidgets.QRadioButton(self.groupBox_control_variate)
        self.radioButton_cv_standard.setGeometry(QtCore.QRect(20, 20, 89, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.radioButton_cv_standard.setFont(font)
        self.radioButton_cv_standard.setChecked(True)
        self.radioButton_cv_standard.setObjectName("radioButton_cv_standard")
        self.radioButton_cv_geo = QtWidgets.QRadioButton(self.groupBox_control_variate)
        self.radioButton_cv_geo.setGeometry(QtCore.QRect(20, 40, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.radioButton_cv_geo.setFont(font)
        self.radioButton_cv_geo.setAcceptDrops(False)
        self.radioButton_cv_geo.setObjectName("radioButton_cv_geo")
        self.verticalLayout_asian_pars.addWidget(self.groupBox_control_variate)
        self.widget_asset2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_asset2.setGeometry(QtCore.QRect(370, 160, 161, 331))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.widget_asset2.setFont(font)
        self.widget_asset2.setObjectName("widget_asset2")
        self.lineEdit_corr = QtWidgets.QLineEdit(self.widget_asset2)
        self.lineEdit_corr.setGeometry(QtCore.QRect(20, 300, 121, 24))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit_corr.setFont(font)
        self.lineEdit_corr.setText("")
        self.lineEdit_corr.setObjectName("lineEdit_corr")
        self.label_corr = QtWidgets.QLabel(self.widget_asset2)
        self.label_corr.setGeometry(QtCore.QRect(20, 280, 121, 15))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_corr.setFont(font)
        self.label_corr.setObjectName("label_corr")
        self.groupBox_asset2 = QtWidgets.QGroupBox(self.widget_asset2)
        self.groupBox_asset2.setGeometry(QtCore.QRect(0, 0, 161, 261))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.groupBox_asset2.setFont(font)
        self.groupBox_asset2.setObjectName("groupBox_asset2")
        self.label_stock_price_2 = QtWidgets.QLabel(self.groupBox_asset2)
        self.label_stock_price_2.setGeometry(QtCore.QRect(20, 30, 121, 15))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_stock_price_2.setFont(font)
        self.label_stock_price_2.setObjectName("label_stock_price_2")
        self.label_vol2 = QtWidgets.QLabel(self.groupBox_asset2)
        self.label_vol2.setGeometry(QtCore.QRect(20, 180, 121, 15))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_vol2.setFont(font)
        self.label_vol2.setObjectName("label_vol2")
        self.lineEdit_vol2 = QtWidgets.QLineEdit(self.groupBox_asset2)
        self.lineEdit_vol2.setGeometry(QtCore.QRect(20, 200, 121, 24))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit_vol2.setFont(font)
        self.lineEdit_vol2.setObjectName("lineEdit_vol2")
        self.lineEdit_stock_price_2 = QtWidgets.QLineEdit(self.groupBox_asset2)
        self.lineEdit_stock_price_2.setGeometry(QtCore.QRect(20, 50, 121, 24))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.lineEdit_stock_price_2.setFont(font)
        self.lineEdit_stock_price_2.setObjectName("lineEdit_stock_price_2")
        self.groupBox_conf = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_conf.setGeometry(QtCore.QRect(590, 350, 131, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.groupBox_conf.setFont(font)
        self.groupBox_conf.setObjectName("groupBox_conf")
        self.label_result_value_2 = QtWidgets.QLabel(self.groupBox_conf)
        self.label_result_value_2.setGeometry(QtCore.QRect(0, 60, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_result_value_2.setFont(font)
        self.label_result_value_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_result_value_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_result_value_2.setText("")
        self.label_result_value_2.setObjectName("label_result_value_2")
        self.label_result_value_1 = QtWidgets.QLabel(self.groupBox_conf)
        self.label_result_value_1.setGeometry(QtCore.QRect(0, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_result_value_1.setFont(font)
        self.label_result_value_1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_result_value_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_result_value_1.setText("")
        self.label_result_value_1.setObjectName("label_result_value_1")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(590, 280, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_result_value = QtWidgets.QLabel(self.groupBox_3)
        self.label_result_value.setGeometry(QtCore.QRect(0, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_result_value.setFont(font)
        self.label_result_value.setFrameShape(QtWidgets.QFrame.Box)
        self.label_result_value.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_result_value.setText("")
        self.label_result_value.setObjectName("label_result_value")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 20, 391, 21))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(590, 60, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(590, 110, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setObjectName("label_4")
        OptionPricer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OptionPricer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 784, 23))
        self.menubar.setObjectName("menubar")
        self.menuAa = QtWidgets.QMenu(self.menubar)
        self.menuAa.setObjectName("menuAa")
        OptionPricer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OptionPricer)
        self.statusbar.setObjectName("statusbar")
        OptionPricer.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(OptionPricer)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(OptionPricer)
        self.actionExit.setObjectName("actionExit")
        self.actionReadme = QtWidgets.QAction(OptionPricer)
        self.actionReadme.setObjectName("actionReadme")
        self.menuAa.addAction(self.actionExit)
        self.menubar.addAction(self.menuAa.menuAction())

        self.retranslateUi(OptionPricer)
        QtCore.QMetaObject.connectSlotsByName(OptionPricer)

    def retranslateUi(self, OptionPricer):
        _translate = QtCore.QCoreApplication.translate
        OptionPricer.setWindowTitle(_translate("OptionPricer", "Option Pricer by Group 19"))
        self.label.setText(_translate("OptionPricer", "Exercise Style:"))
        self.comboBox_kindof_option.setItemText(0, _translate("OptionPricer", "European"))
        self.comboBox_kindof_option.setItemText(1, _translate("OptionPricer", "American"))
        self.comboBox_kindof_option.setItemText(2, _translate("OptionPricer", "Asian"))
        self.comboBox_kindof_option.setItemText(3, _translate("OptionPricer", "Implied Volatility"))
        self.groupBox.setTitle(_translate("OptionPricer", "Option Type:"))
        self.radioButton_call.setText(_translate("OptionPricer", "Call"))
        self.radioButton_put.setText(_translate("OptionPricer", "Put"))
        self.pushButton_calculate.setText(_translate("OptionPricer", "Calculate"))
        self.groupBox_asset1.setTitle(_translate("OptionPricer", "Asset1"))
        self.label_stock_price.setText(_translate("OptionPricer", "Stock Price: ($)"))
        self.label_strike_price.setText(_translate("OptionPricer", "Strike Price: ($)"))
        self.label_strike_price_2.setText(_translate("OptionPricer", "Interest Rate: (%)"))
        self.label_vol1.setText(_translate("OptionPricer", "Volatility: (%)"))
        self.label_maturity.setText(_translate("OptionPricer", "Maturity: (years)"))
        self.label_step.setText(_translate("OptionPricer", "Step:"))
        self.label_paths.setText(_translate("OptionPricer", "Path:"))
        self.groupBox_numof_assets.setTitle(_translate("OptionPricer", "Number of assets:"))
        self.radioButton_asset_single.setText(_translate("OptionPricer", "Single"))
        self.radioButton_asset_basket.setText(_translate("OptionPricer", "Basket"))
        self.groupBox_pricing_type.setTitle(_translate("OptionPricer", "Type of pricer:"))
        self.radioButton_type_geo.setText(_translate("OptionPricer", "Geometric"))
        self.radioButton_type_arith.setText(_translate("OptionPricer", "Arithmetic"))
        self.groupBox_control_variate.setTitle(_translate("OptionPricer", "Control Variate:"))
        self.radioButton_cv_standard.setText(_translate("OptionPricer", "None"))
        self.radioButton_cv_geo.setText(_translate("OptionPricer", "Geo Asian"))
        self.label_corr.setText(_translate("OptionPricer", "Correlation: (%)"))
        self.groupBox_asset2.setTitle(_translate("OptionPricer", "Asset 2"))
        self.label_stock_price_2.setText(_translate("OptionPricer", "Stock Price: ($)"))
        self.label_vol2.setText(_translate("OptionPricer", "Volatility: (%)"))
        self.groupBox_conf.setTitle(_translate("OptionPricer", "Confidence:"))
        self.groupBox_3.setTitle(_translate("OptionPricer", "Result"))
        self.label_2.setText(_translate("OptionPricer", "Option Pricer by Group19"))
        self.label_3.setText(_translate("OptionPricer", "ZHAN Hui 3035249227"))
        self.label_4.setText(_translate("OptionPricer", "LIU Jiahe 3035237365"))
        self.menuAa.setTitle(_translate("OptionPricer", "Program"))
        self.actionAbout.setText(_translate("OptionPricer", "About"))
        self.actionAbout.setShortcut(_translate("OptionPricer", "F12"))
        self.actionExit.setText(_translate("OptionPricer", "Exit"))
        self.actionExit.setShortcut(_translate("OptionPricer", "Esc"))
        self.actionReadme.setText(_translate("OptionPricer", "readme"))

